export enum AREA_TYPES {
  SARJAPUR_ROAD = "SARJAPUR ROAD",
  BELLANDUR = "BELLANDUR",
  MARATHAHALLI = "MARATHAHALLI",
  KORAMANGALA = "KORAMANGALA",
  INDIRANAGAR = "INDIRANAGAR",
  WHITEFIELD = "WHITEFIELD",
  ELECTRONIC_CITY = "ELECTRONIC CITY",
  HSR = "HSR",
  BTM = "BTM",
  JP_NAGAR = "JP NAGAR",
  BANASHANKARI = "BANASHANKARI",
  JAYANAGAR = "JAYANAGAR",
  RAJAJINAGAR = "RAJAJINAGAR",
  YESHWANTPUR = "YESHWANTPUR",
}

export type Timing = {
  startTime: any;
  endTime: any;
};

export type SetTiming = React.Dispatch<React.SetStateAction<Timing[]>>;